# Generated by Django 3.1.7 on 2021-03-25 15:04

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_id', models.CharField(blank=True, max_length=20, primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=20, unique=True)),
                ('firstcontact_name', models.CharField(max_length=20)),
                ('firstcontact_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('secondcontact_name', models.CharField(max_length=20)),
                ('secondcontact_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
            ],
        ),
    ]
